--- #YAML:1.0
name:               XML-Malware
version:            0.00_02
abstract:           Perl extension for representing malware samples in XML 
author:
    - Wes Young <wes@barely3am.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::Compile:  1.15
    XML::LibXML:   1.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
